name: mreminders
options:
  bundleIdPrefix: com.miro
  deploymentTarget:
    macOS: "14.0"
  minimumXcodeGenVersion: "2.38.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  mreminders:
    type: application
    platform: macOS
    sources:
      - path: mreminders
    settings:
      base:
        INFOPLIST_FILE: mreminders/Info.plist
        CODE_SIGN_ENTITLEMENTS: mreminders/mreminders.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.miro.mreminders
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: mreminders
        COMBINE_HIDPI_IMAGES: YES

  mremindersTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: mremindersTests
    dependencies:
      - target: mreminders
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.miro.mreminders.tests
        GENERATE_INFOPLIST_FILE: YES
